# Generated by Django 6.1.1 on 2026-09-25 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_exam_date_exam_date_exam_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
